### ISSUE TITLE
Cant install on a non-docker server

### ISSUE THREAD

**Issue by nahtnam** [davidcelis/new_relic-discourse#8]
Hey!

I am trying to get this to work on a non docker server.

I cloned the repo into the plugins folder, and set the env variables. Then I installed the exact version of the gem using `gem install`. New relic is saying that the app isnt running though.

Any suggestions?

**Comment by davidcelis** [comment]
Hey; there was a problem with the newrelic.yml file that's included with the plugin. I just fixed it in 81dea54 so could you try again?

**Comment by nahtnam** [comment]
@davidcelis Working. Thanks! :)
